### ISSUE TITLE
Giskard setup using Docker Compose fails

### ISSUE THREAD

**Issue by sprathod369** [Giskard-AI/giskard#1353]
### Issue Type

Bug

### Source

docker

### Giskard Library Version

n/a

### Giskard Server Version

Latest based on docker definitions

### OS Platform and Distribution

Linux Ubuntu 20x

### Installed python packages

```shell
n/a
```

### Current Behaviour?

```shell
Running "docker-compose build" should have successfully build all the docker images and components which did not happen. This is the error

:~/giskard# docker-compose build
[+] Building 0.0s (0/0)
could not find /root/giskard/python-client/docker: stat /root/giskard/python-client/docker: no such file or directory
```

### Standalone code OR list down the steps to reproduce the issue

```shell
1) Clone the Giskard repo from https://github.com/Giskard-AI/giskard.git
2) cd giskard
3) Run docker-compose up

Error:
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2532142894/Dockerfile: no such file or directory
```

### Relevant log output

```shell
Seems a number of DockerFiles are missing in the cloned repo from https://github.com/Giskard-AI/giskard.git
e.g. No Dockerfile in in the path mentioned in docker-compose at giskard/python-client/
```

**Comment by PAARTH2608** [comment]
HI, I would like to work on this issue, can you please assign it to me?

**Comment by kevinmessiaen** [comment]
@PAARTH2608 As of today we provide a single docker image [giskardai/giskard](https://hub.docker.com/r/giskardai/giskard).

The docker compose is not working since the image used aren't build anymore. I think we can simply cleanup by deleting those files.

**Comment by PAARTH2608** [comment]
@kevinmessiaen can you please eloborate on which files are to be cleaned up as I cant find any docker or docker-compose files in the cloned repo?

**Comment by kevinmessiaen** [comment]
@PAARTH2608 My bad, those files has been removed from this repository already...
