### ISSUE TITLE
Is it possible to use Giskard for computer vision / images?

### ISSUE THREAD

**Issue by j-adamczyk** [Giskard-AI/giskard#1453]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/Giskard-AI/giskard/issues?q=is%3Aissue).

## ❓ Question

As in title, is it possible to use Giskard for computer vision, i.e. image datases? I am using HuggingFace for vision CNN models (ResNet, ConvNeXt etc.) and would like to test them.

**Comment by luca-martial** [comment]
Thanks for the question @j-adamczyk ! We're in the process of working on support computer vision. Would be great to get your feedback on our upcoming work.

**Comment by luca-martial** [comment]
Will report back once support is added

**Comment by yassineAlouini** [comment]
@luca-martial Any chance you are starting to work on this for computer vision? I would be happy to research the state-of-the art about perturbation methods for binary classification for CV let's say to get started. Let me know if this could help. :ok_hand:

**Comment by luca-martial** [comment]
> @luca-martial Any chance you are starting to work on this for computer vision? I would be happy to research the state-of-the art about perturbation methods for binary classification for CV let's say to get started. Let me know if this could help. 👌

@yassineAlouini Thanks for suggesting this! We'll get back to you asap with more info!

**Comment by henchaves** [comment]
> @luca-martial Any chance you are starting to work on this for computer vision? I would be happy to research the state-of-the art about perturbation methods for binary classification for CV let's say to get started. Let me know if this could help. 👌

Hey @yassineAlouini, now we have a dedicated repo for CV: https://github.com/Giskard-AI/giskard-vision

**Comment by yassineAlouini** [comment]
> > @luca-martial Any chance you are starting to work on this for computer vision? I would be happy to research the state-of-the art about perturbation methods for binary classification for CV let's say to get started. Let me know if this could help. 👌
> 
> Hey @yassineAlouini, now we have a dedicated repo for CV: https://github.com/Giskard-AI/giskard-vision

That's great news!
