### ISSUE TITLE
Feature: add OCR typos transformation to transformation functions catalog

### ISSUE THREAD

**Issue by luca-martial** [Giskard-AI/giskard#1565]
## 🚀 Feature Request

Giskard currently implements a [regular typo transformation](https://github.com/Giskard-AI/giskard/blob/main/giskard/scanner/robustness/text_transformations.py#L70) in its robustness scan. We are looking to implement a similar transformation which is based on typos that frequently occur after OCR processing.

Example: "Their cat eats everyday" -> "Tbeir c^at eats evervd^av"

## 🔈 Motivation

This will enhance the completeness of Giskard's catalog.

**Comment by goyalpramod** [comment]
I believe I can work on this well, can you kindly assign this to me? @luca-martial

**Comment by luca-martial** [comment]
Thanks @goyalpramod ! I'm assigning you now
