### ISSUE TITLE
Feature: add speech-to-text typos transformation to transformation functions catalog

### ISSUE THREAD

**Issue by luca-martial** [Giskard-AI/giskard#1566]
## 🚀 Feature Request

Giskard currently implements a [regular typo transformation](https://github.com/Giskard-AI/giskard/blob/main/giskard/scanner/robustness/text_transformations.py#L70) in its robustness scan. We are looking to implement a similar transformation which is based on typos that frequently occur after speech-to-text processing.

Example: "NASDAQ dropped by 2.1%" -> "Attack drop by 21%"

## 🔈 Motivation

This will enhance the completeness of Giskard's catalog.

**Comment by goyalpramod** [comment]
Hello @luca-martial I would like to work on this issue, could you kindly assign it to me? 
I had a few initial questions as well. 
1. I believe the structure will be similar to TextTypoTransformation but we have to take into consideration that mistakes that are made in speech to text for example "Too" may be misclassified as "Two". So the code should reflect that. (Assuming English is the primary target language) 
2. How are filler words supposed to be handled? for example "humm", "uh", "ah".

**Comment by luca-martial** [comment]
Thanks @goyalpramod ! For (1) yes exactly, for (2) I don't believe you will need to transform filler words. Let me know if you have any other question!
