### ISSUE TITLE
Feature: add number-to-word transformation to transformation functions catalog

### ISSUE THREAD

**Issue by luca-martial** [Giskard-AI/giskard#1567]
## 🚀 Feature Request

Giskard currently implements a [transformations](https://github.com/Giskard-AI/giskard/blob/main/giskard/scanner/robustness/text_transformations.py) in its robustness scan. We are looking to implement a new transformation which transforms numbers to words.

Example: "Around 153 people were recovered" -> "Around one hundred fifty three people were recovered"

## 🔈 Motivation

This will enhance the completeness of Giskard's catalog.

**Comment by sagar118** [comment]
Hello Luca, Is it fair to assume the text would be only in the English language? Do we want to handle the target language as a choice of input?

There is a Python package [num2words](https://github.com/savoirfairelinux/num2words) that converts numbers to words and has multi-language support.

**Comment by luca-martial** [comment]
@sagar118 thanks for your interest! It's fair to say that text will be in English for > 80% of cases. Multi-language support would be a nice addition though. I'll let you decide based on feasibility!

**Comment by sagar118** [comment]
Sounds good.

Do we want to convert all numbers to text? For instance, numbers can be part of dates, emails, and URLs. Hence, should the expected behavior be to change all numbers to text or only for a particular scenario like plain numbers?

**Comment by luca-martial** [comment]
@sagar118 you can start with a v1 that converts all numbers. We can reassess later if needed!

**Comment by sagar118** [comment]
Sure. That sounds good.
