### ISSUE TITLE
Update password hashing to use SHA-256 for enhanced security!

### ISSUE THREAD

**Issue by amdjedbens** [Giskard-AI/giskard#1682]
The change involves replacing the existing code `hashlib.md5(string.encode()).hexdigest()` with the more robust `hashlib.sha256(string.encode()).hexdigest()`.

This adjustment enhances resistance against potential security threats and aligns with best practices for cryptographic hash functions.

**Comment by PAARTH2608** [comment]
Hi, I would like to work on this issue, could you assign it to me?

**Comment by kevinmessiaen** [comment]
Hello @PAARTH2608 

Unfortunately this issue require us to update the Giskard Hub that is closed source. Only updating the hash method for the Giskard Library client will produce authentication error (since another hash is expected).
