### ISSUE TITLE
Reduce percentage float precision in display results details

### ISSUE THREAD

**Issue by fran6w** [Giskard-AI/giskard#1730]
## 🚀 Feature Request

Reduce percentage float precision in display results details

## 🔈 Motivation

The % might be shown with many useless decimals

## 🛰 Alternatives

Round up all % to 2 decimals

## 📎 Additional context

Example with Titanic:
For records in the dataset where `text_length(Name)` < 28.500, we found a significantly higher number of overconfident wrong predictions (33 samples, corresponding to 55.932203389830505% of the wrong predictions in the data slice).

**Comment by luca-martial** [comment]
Great request @fran6w ! I'll mark this as a good first issue and see if community contributors are open to take it. 

Let me know if you prefer that I assign it to you instead!

**Comment by fran6w** [comment]
Thank you, but I am not enough familiar with Giskard's code.

**Comment by luca-martial** [comment]
> Thank you, but I am not enough familiar with Giskard's code.

No problem, thanks for contributing a request!

**Comment by asselindebeauville** [comment]
I can help with this issue. I see you're already using 1 decimal in the `UnderconfidenceDetector`. Do you want to standardize it to 1 or 2 decimals? Please let me know and I'll update both accordingly.

**Comment by luca-martial** [comment]
> I can help with this issue. I see you're already using 1 decimal in the `UnderconfidenceDetector`. Do you want to standardize it to 1 or 2 decimals? Please let me know and I'll update both accordingly.

Great, 2 decimals is good. Note this should only be for the final display

**Comment by asselindebeauville** [comment]
I made the change in #1754, here's what it looks like now:

| Vulnerability | Description |
|---------------|-------------|
| Overconfidence | For records in the dataset where `text_length(sentence)` >= 65.500, we found a significantly higher number of overconfident wrong predictions (59 samples, corresponding to 22.01% of the wrong predictions in the data slice). |

**Comment by asselindebeauville** [comment]
PR #1754 has been merged. This issue may be closed.
