### ISSUE TITLE
Add text transform to remove accents

### ISSUE THREAD

**Issue by kevinmessiaen** [Giskard-AI/giskard#1741]
## 🚀 Feature Request

Add a text transform to remove accents.

Example: `C'est l'été` becomes `C'est l'ete`

The transformation should be able to work with various characters and both lowercase and uppercase:

`çà et là` becomes `ca et la`
`Tiếng Việt` becomes `Tieng Viet`
`État` becomes `Etat`
and so on

It might be worth to have a perturbation rate parameters (default 100%)  

## 🔈 Motivation

We want to be able to test model with common text variation in languages using accents.

**Comment by asselindebeauville** [comment]
Hi, I am interested in working on this issue.

**Comment by luca-martial** [comment]
> Hi, I am interested in working on this issue.

Great to hear that @asselindebeauville - I just assigned it to you!
