### ISSUE TITLE
How does it help with Model Interpretability and Explainability for Black-box model architecture

### ISSUE THREAD

**Issue by mrbestnaija** [Giskard-AI/giskard#1850]
## Checklist

- [ ] I've searched the project's [`issues`](https://github.com/Giskard-AI/giskard/issues?q

## ❓ Question

Is Giskard model-agnostic and what is the performance on black-box models?

How does  Giskard assist in model interpretability concerning fairness, security and privacy considerations?

Is it possible to [...]?

**Comment by mrbestnaija** [comment]
I was unable to fully explore Giskard due to computational resource constraint. However, Giskard provides tools for evaluating models before serving in production. The experimental nature of Giskard would need further exploration for the inclusion of advanced model debugging features that pertain to network and infrastructure resource usage and adversarial activities in a production environment.

**Comment by luca-martial** [comment]
Hey @mrbestnaija here are our docs: https://docs.giskard.ai/en/stable/

Debugging is something that's available in our enterprise product only. Hope that answers the question!
