### ISSUE TITLE
huggingface models as client?

### ISSUE THREAD

**Issue by kbmlcoding** [Giskard-AI/giskard#1931]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/Giskard-AI/giskard/issues?q=is%3Aissue).

## ❓ Question

Is there any good example of how to use huggingface models and eventually perform giskard scan
How can I [...]?

**Comment by shasss447** [comment]
https://github.com/Giskard-AI/giskard/blob/main/giskard/models/huggingface.py
check this out
