### ISSUE TITLE
Contributing to examples/tutorials

### ISSUE THREAD

**Issue by cyberholics** [Giskard-AI/giskard#1951]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/Giskard-AI/giskard/issues?q=is%3Aissue).

## ❓ Question

I am interested in making tutorials or examples on how to use Giskard, maybe technical articles as well. I have knowledge of using giskard, how do I start making these contributions? Should i create these tutorials on my blog first?

**Comment by henchaves** [comment]
Hey @cyberholics, thanks for your interest in helping us.

If you prefer, You can create a tutorial notebook. 
For example, all notebooks displayed on giskard docs are available here: https://github.com/Giskard-AI/giskard/tree/main/docs/reference/notebooks
Then, you just have to submit a PR to add your contribution.

**Comment by cyberholics** [comment]
Sounds great; look out for my PR soon.
