### ISSUE TITLE
Unresolved Version Conflict for Langchain-community

### ISSUE THREAD

**Issue by jeffersonqiu** [Giskard-AI/giskard#1957]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/Giskard-AI/giskard/issues?q=is%3Aissue).

## ❓ Question

I am unable to resolve dependencies requirement between langchain, langchain-community and giskard[llm]. I am using poetry as dependencies management tool and this is what I am getting: 

Because no versions of langchain-community match >0.2.5,<0.3.0
 and langchain-community (0.2.5) depends on langchain (>=0.2.5,<0.3.0), langchain-community (>=0.2.5,<0.3.0) requires langchain (>=0.2.5,<0.3.0).
So, because giskard-project depends on both langchain (<=0.0.301) and langchain-community (^0.2.5), version solving failed.

Is there any version of langchain, langchain-community and giskard[llm] that can run well together?

## 📎 Additional context

Here is my current depencies before adding langchain-community: 
python = ">=3.9,<3.12"
giskard = {extras = ["llm"], version = "^2.14.0"}
langchain = "<=0.0.301"
pypdf = "<=3.17.0"
faiss-cpu = "<=1.7.4"
openai = "<=0.28.1"
tiktoken = "<=0.5.1"
python-dotenv = "^1.0.1"

**Comment by kevinmessiaen** [comment]
Hello,

Giskard doesn't require `langchain <=0.0.301`, however you might have added the requirement when exploring an old demo notebook. You can safely upgrade `langchain` and `openai` to run Giskard without any issue.
