### ISSUE TITLE
Support python 3.12

### ISSUE THREAD

**Issue by baswenneker** [Giskard-AI/giskard#1976]
## 🚀 Feature Request

Support python 3.12

## 🔈 Motivation

It was released in oktober 2023, my project uses 3.12 and can't downgrade to 3.12. 

## 🛰 Alternatives

...

## 📎 Additional context

...

**Comment by lestarr** [comment]
Please do that. All your sub libraries and modules can be used under python 3.12

**Comment by mattbit** [comment]
We had issues with `torch` which prevented us from supporting Python 3.12 immediately. I just checked that PyTorch 2.4 which was released end of July is finally compatible with 3.12, we will give it a go!
