### ISSUE TITLE
when ı am creating knowledgebase, my codes here:

### ISSUE THREAD

**Issue by Khaliq88** [Giskard-AI/giskard#1986]
when ı am creating knowledgebase, my codes here:

from giskard.rag import KnowledgeBase
import os
import giskard
from giskard.llm.client.mistral import MistralClient

api_key = os.environ["MISTRAL_API_KEY"]
model = "mistral-large-latest"

mc = MistralClient()
giskard.llm.set_default_client(mc)
knowledge_base=KnowledgeBase(df_base)

ı get this error:

OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

_Originally posted by @klncgty in https://github.com/Giskard-AI/giskard/discussions/1983_

**Comment by Vikas9758** [comment]
It is because by default knowledge base uses openai embeddings.So in parameter with df base also pass your embedding model that you have used earlier.
`knowledge_base=Knowledge base(df_base,embedding=FastembedEmbeddings())`
