### ISSUE TITLE
When will the API documentation for the RAG Evaluation Toolkit be completed?

### ISSUE THREAD

**Issue by LordSyd** [Giskard-AI/giskard#2032]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/Giskard-AI/giskard/issues?q=is%3Aissue).

## ❓ Question

At the moment all articles under this URL https://docs.giskard.ai/en/stable/reference/rag-toolset/index.html are empty. When can we expect to get documentation for the API of the RAGET?

**Comment by henchaves** [comment]
@kevinmessiaen, is it related to #2037 ?

**Comment by kevinmessiaen** [comment]
> @kevinmessiaen, is it related to #2037 ?

Yes it is relates but not fixed yet. I need to find you what is making those page empty when building the doc for production. When building for dev locally those page are well populated.

**Comment by henchaves** [comment]
Hey @LordSyd, could you check again the docs webpage? We have fixed it.
https://docs.giskard.ai/en/latest/reference/rag-toolset/index.html
