### ISSUE TITLE
Ollama Embeddings

### ISSUE THREAD

**Issue by nobad4rt** [Giskard-AI/giskard#2035]
At the moment, the article here https://docs.giskard.ai/en/latest/open_source/setting_up/index.html doesn't mention about how to set up the Ollama client for embedding models. Is this possible or not? If it is, can anyone help show me how?

**Comment by henchaves** [comment]
Hello @nobad4rt, thanks for opening this issue.

Indeed, we should also add the code of how to set up the client for embedding models.
I just opened an internal card so we can update the docs as soon as possible.

In the meanwhile, you can use this code snippet as a base of how to do that:

```python
from openai import OpenAI
from giskard.llm.client.openai import OpenAIClient
from giskard.llm.embeddings.openai import OpenAIEmbedding

_client = OpenAI(base_url="http://localhost:11434/v1/", api_key="ollama")

llm_client = OpenAIClient(model="llama3.2", client=_client, json_mode=True)
emb_client = OpenAIEmbedding(model="nomic-embed-text", client=_client)

from giskard.llm import set_default_client
from giskard.llm.embeddings import set_default_embedding

set_default_client(llm_client)
set_default_embedding(emb_client)
```

**Comment by henchaves** [comment]
GSK-3835 opened to solve this issue
