### ISSUE TITLE
Import error with RAGAS v0.2.2

### ISSUE THREAD

**Issue by PierreMesure** [Giskard-AI/giskard#2051]
### Issue Type

Bug

### Source

source

### Giskard Library Version

2.15.2

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.13

### Installed python packages

```shell
ragas==0.2.2
```

### Current Behaviour?

RAGAS just [removed the file ragas.llms.prompt.py](https://github.com/explodinggradients/ragas/pull/1535) from their codebase in their latest minor release (v0.2.2) and this is breaking Giskard which is trying to [import the file](https://github.com/Giskard-AI/giskard/blob/750db5c8f87193118d64d71ccbfe513e5132ecb7/giskard/rag/metrics/ragas_metrics.py#L17).

The help message is not informative and even misleading so it would be good to change it:
```
ImportError: Package ragas.llms.prompt is missing, it is required for the computation of RAGAS metrics. You can install it with `pip install ragas.llms.prompt`.
```

### Standalone code OR list down the steps to reproduce the issue

```shell
from giskard.rag.metrics.ragas_metrics import ragas_context_recall, ragas_context_precision
```

### Relevant log output

```shell
giskard\rag\metrics\ragas_metrics.py", line 17, in <module>
    from ragas.llms.prompt import PromptValue
ModuleNotFoundError: No module named 'ragas.llms.prompt'

giskard\rag\metrics\ragas_metrics.py", line 23, in <module>
    raise ImportError(
ImportError: Package ragas.llms.prompt is missing, it is required for the computation of RAGAS metrics. You can install it with `pip install ragas.llms.prompt`.
```

**Comment by henchaves** [comment]
Hello @PierreMesure, we have just released giskard v2.15.3 which solves this bug!
