### ISSUE TITLE
Outdated error message

### ISSUE THREAD

**Issue by PierreMesure** [Giskard-AI/giskard#2055]
### Issue Type

Bug

### Source

source

### Giskard Library Version

latest

### Current Behaviour?

According to [this error message](https://github.com/Giskard-AI/giskard/blob/c0b167d4da1923c474ddf817234195c9c5ca031c/giskard/rag/metrics/ragas_metrics.py#L109), it's possible to pass a parameter called "retrieved_documents" but [it seems to be deprecated](https://github.com/orgs/Giskard-AI/discussions/1945#discussioncomment-9649292).

### Standalone code OR list down the steps to reproduce the issue

Run evaluate() with an answer_fn returning str instead of AgentAnswer.

**Comment by alexcombessie** [comment]
Hey @PierreMesure - Thanks for raising this. 

@henchaves would you have some time to have a look?

**Comment by henchaves** [comment]
Hey @PierreMesure, thanks for reporting this.
A PR was opened to update the error message: https://github.com/Giskard-AI/giskard/pull/2062
It well be merged soon!
