### ISSUE TITLE
infinite build times on hf private spaces using docker image

### ISSUE THREAD

**Issue by Josephrp** [Giskard-AI/giskard#2078]
### Issue Type

Bug

### Source

docker

### Giskard Library Version

not sure i just used the gui

### OS Platform and Distribution

huggingface spaces (not sure , used the image from hf)

### Python version

not sure , didnt check, sorry !

### Installed python packages

```shell
from docker image
```

### Current Behaviour?

```shell
infinite build times on private spaces deployment on huggingface
```

### Standalone code OR list down the steps to reproduce the issue

```shell
using the hf gui to launch docker image on private spaces
```

### Relevant log output

```shell
https://huggingface.co/spaces/open-acc/giskard?logs=build

===== Build Queued at 2024-11-20 19:52:18 / Commit SHA: ecc877b =====
```

**Comment by alexcombessie** [comment]
Hey @Josephrp  - Sorry, we've deprecated this Docker image in favour of a newer product: https://www.giskard.ai/products/llm-evaluation-hub

We don't distribute this product on HF spaces but via hosted SaaS or on-private-Cloud k8s installation. Could you give us more information of you AI use case and testing need?

@Inokinoki could you add a note on the documentation on huggingface side to remove it and mark the deprecation?

**Comment by Josephrp** [comment]
well noted with thanks , i'll reach out to both huggingface and giskard with the information requested above
