### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by p4puniya** [Giskard-AI/giskard#273]
The PFA file *Worker* is not found. And the said folder contains various errors when opened in my IDE.

https://github.com/Giskard-AI/giskard/blob/92d1deb14bbe47a7df222def72d5297ce0cbb50f/giskard-server/src/main/java/ai/giskard/ml/MLWorkerClient.java#L10

![Screenshot from 2022-09-27 23-23-11](https://user-images.githubusercontent.com/60355338/192600796-74bd5fb1-6a49-43af-9f7a-7d89ed19e2d1.png)

**Comment by p4puniya** [comment]
I guess the said file is either removed or moved to a new destination. If possible can someone guide me on how to resolve this issue? I'm just starting with open-source so please bear with me.😅

**Comment by andreybavt** [comment]
Hi @p4puniya ,
The missing files are auto-generated during the build of the project. To run the build you can execute `./gradlew build` from the root of the cloned repo.

We're working on improving developers' documentation, for now, there's a Notion page that describes how to set up Giskard for local development using Intellij Idea (but you may find it useful for VS Code too).
https://giskard.notion.site/Running-Giskard-on-local-without-docker-6b5b4f47a0da4b4a9851bbf65199c5cd

**Comment by p4puniya** [comment]
Hi @andreybavt ,
I tried building the project but it shows *APPLICATION FAILED TO START*
Here's the description and the action:
Description:
Parameter 2 of constructor in ai.giskard.service.ProjectService required a bean of type 'ai.giskard.web.dto.mapper.GiskardMapper' that could not be found.
Action:
Consider defining a bean of type 'ai.giskard.web.dto.mapper.GiskardMapper' in your configuration.

**Comment by olla-dev** [comment]
Hello, 

Reposting this here from discussion on discord (thanks for the help).

This should solve your problem:

> classes from ai.giskard.worker are autogenerated from GRPC proto file located in giskard-server/ml-worker-proto/proto/ml-worker.proto
> 
> This ml-worker-proto directory is a submodule, so to fetch it you can run this command from the root of giskard repository
> `git submodule update --init --recursive -q`
> 
> next, to generate the missing java files you can run
> `./gradlew :giskard-server:cleanGenerated :giskard-server:generateProto`

**Comment by andreybavt** [comment]
Hi everyone,

We decided to simplify Giskard repo structure and merged 3 repos (giskard, giskard-client, and ml-worker-proto) into the main `giskard` repo. This allowed us to get rid of the proto file submodule, so no need to pull submodule recursively now. 

Starting giskard in dev mode should be now done with just

`./gradlew start --parallel`

Check out the dev readme for more details
https://github.com/Giskard-AI/giskard/blob/main/README.dev.md
