### ISSUE TITLE
Class based model upload

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#384]
[GSK-336](https://giskard.youtrack.cloud/issue/GSK-336)

Project: Giskard
Reporter: aavtomonov
Created: 2022-11-07

**Comment by rabah-khalek** [comment]
List of daughter issues:
- https://github.com/Giskard-AI/giskard/issues/374
- https://github.com/Giskard-AI/giskard/issues/398
- https://github.com/Giskard-AI/giskard/issues/402
- https://github.com/Giskard-AI/giskard/issues/405
