### ISSUE TITLE
Improve the error log of `_validate_model_is_pickleable`

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#398]
[GSK-387](https://giskard.youtrack.cloud/issue/GSK-387)

Expanding the model upload error to:

```
ValueError: Unable to pickle or unpickle model on Giskard -- check if the uploaded model is supported by Giskard: https://docs.giskard.ai/verified-models for more info
```

related to: <https://github.com/Giskard-AI/giskard/issues/374>

and: <https://giskard.youtrack.cloud/agiles/121-12/current?issue=GSK-336>

Project: Giskard
Reporter: rabah
Created: 2022-11-28

**Comment by andreybavt** [comment]
@rabah-khalek is this one still in progress?

**Comment by rabah-khalek** [comment]
@andreybavt yes. This is a daughter issue of https://github.com/Giskard-AI/giskard/issues/384. I can take care of linking the related issues to the model-API if you prefer.
