### ISSUE TITLE
H2O models unable to unpickle on Giskard

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#399]
[GSK-388](https://giskard.youtrack.cloud/issue/GSK-388)

github-issue: <https://github.com/Giskard-AI/giskard/issues/374>

Project: Giskard
Reporter: rabah
Created: 2022-11-28

**Comment by rabah-khalek** [comment]
just to be clear: H2O models serialization won't be supported for giskard v2.0
