### ISSUE TITLE
TFAutoModel has issues while unpickling

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#405]
[GSK-285](https://giskard.youtrack.cloud/issue/GSK-285)

TFAutomodel does not have the .bert function of TFBertModel which solves the known unpicking issue (<https://github.com/huggingface/transformers/issues/3627>) forcing the users to use only TFBertModel instead of TFAutomodel. This is NOT OUR BUG but we will face integration issues in future. Creating card to keep track of the issue.

Project: Giskard
Reporter: princy
Created: 2022-09-16

**Comment by AliNazeri** [comment]
I have same issue unpickling the model, but I found solved for model.save() and load_model. if the [link](https://github.com/huggingface/transformers/issues/3627) helps
