### ISSUE TITLE
remove Dataset.columnTypes deprecated property

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#468]
[GSK-258](https://giskard.youtrack.cloud/issue/GSK-258)

https://github.com/Giskard-AI/giskard/blob/24d69aca2a4f8a58629150818490bd26aa0adab5/giskard-server/src/main/java/ai/giskard/domain/ml/Dataset.java#L61

Project: Giskard
Reporter: aavtomonov
Created: 2022-08-29

**Comment by dipankr** [comment]
Hey,
Can I work on this?

**Comment by andreybavt** [comment]
Hi @dipankr , this issue is deprecated now, we're releasing a new major version this summer, where the mode/dataset handling has been vastly improved

**Comment by dipankr** [comment]
> Hi @dipankr , this issue is deprecated now, we're releasing a new major version this summer, where the mode/dataset handling has been vastly improved.
> Thanks for offering help

That's great, thank you for the update. 👍
