### ISSUE TITLE
Handle zero division error in performance test

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#492]
[GSK-221](https://giskard.youtrack.cloud/issue/GSK-221)

* for performance test we have, we have the case where we can have zero division error when we do abs(reference  - actual) / reference  .We need to return an error message when reference = 0

Project: Giskard
Reporter: princy
Created: 2022-07-28

**Comment by andreybavt** [comment]
@Googleton I found this card explaining the same issue you fixed. Could you please verify there's no other place in our tests where we divide by a potentially zero value. If everything's fine this issue can be closed

**Comment by andreybavt** [comment]
Yeah, I don't think there's another check upstream that prevents a user to chose an empty actual dataset, so it's best to check it here

**Comment by RagnarokAnsh** [comment]
Hi @andreybavt , I am interested to work on this issue. Can you help me get started.

**Comment by andreybavt** [comment]
Hi @RagnarokAnsh , this particular task has been implemented already, but thanks for offering help. Are you most interested in ML related tasks or engineering?
