### ISSUE TITLE
Add progress information on inspection loading modal

### ISSUE THREAD

**Issue by alexcombessie** [Giskard-AI/giskard#597]
This step is often taking over 30 seconds. With a simple spinner and no information on the progress, it leads the user to wonder if there is not a bug.

It would be a much better UX to have a % progress information

<img width="1409" alt="CleanShot 2022-12-13 at 15 04 28@2x" src="https://user-images.githubusercontent.com/4739848/207354703-e0a516a3-c67f-4a0a-8c2c-1dccc3b0f861.png">

**Comment by Googleton** [comment]
Proposal:

![Screenshot 2022-12-19 at 17 16 16](https://user-images.githubusercontent.com/1703741/208470898-29d485b8-6cd2-425b-9b06-3f337e659168.png)

Any feedback on text or placement?

**Comment by alexcombessie** [comment]
Good proposal! How about "Scoring dataset of {numRows} rows. This operation can take a while..."

And a small vertical space between the message and the loading bar.

**Comment by Googleton** [comment]
At that point in time we do not know the number of rows in the dataset, so getting that information would require some changes to the backend too.

With vertical space:
![Screenshot 2022-12-20 at 10 07 33](https://user-images.githubusercontent.com/1703741/208627739-c99c1d8f-a3fc-4df7-847d-bd043aab2f1f.png)

**Comment by alexcombessie** [comment]
Ok!

Alex Combessie
Co-founder & CEO @ *Giskard*
*Eliminate risks of AI biases*
Website: giskard.ai ( https://bit.ly/364GAGi )
*⭐️ Star us on G itHub ( https://bit.ly/37aWG1y )*
( https://bit.ly/37aWG1y )
