### ISSUE TITLE
Overview always has a teal color even when it's not selected

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#610]
![image](https://user-images.githubusercontent.com/7889985/208401580-d556c0f9-0c41-4a85-90fc-83b99ebe6085.png)

The correct behavior should be the same as for the other tabs - return to regular color once  the category isn't selected

**Comment by p4puniya** [comment]
Hi I would like to solve this issue can U please assign it to me?

**Comment by p4puniya** [comment]
We can close this issue now :)
