### ISSUE TITLE
Remove user access management from open-source version

### ISSUE THREAD

**Issue by alexcombessie** [Giskard-AI/giskard#614]

**Comment by Googleton** [comment]
Changes to settings UI. Data removed from the User page:
<img width="1512" alt="Screenshot 2023-01-03 at 10 16 43" src="https://user-images.githubusercontent.com/1703741/210328828-32dfc6a3-59a0-4743-b86b-f4a0d259c8cf.png">

And added tabs to the settings tab, with General containing the missing info: 
<img width="1512" alt="Screenshot 2023-01-03 at 10 18 24" src="https://user-images.githubusercontent.com/1703741/210329103-df7da5f7-143d-413f-91e0-db6f1d77343f.png">
