### ISSUE TITLE
Error in console when inspecting a model (doesn't impact the inspection)

### ISSUE THREAD

**Issue by Neyrii** [Giskard-AI/giskard#616]
This error occurs in multiple places but doesn't impact the utilisation of giskard. It's caused by the migration to composition API by Vue

![Image](https://user-images.githubusercontent.com/55790616/208918007-9195e88b-5c77-44b7-aa24-4a0bb206247a.png)

**Comment by Googleton** [comment]
Strange issue, Andrey committed this: https://github.com/Giskard-AI/giskard/commit/3e2a8de6170b0f0de7c8df6881924d13b8b63d6d which should be a fix for it...
