### ISSUE TITLE
Inspection progress-bar displaying `NaN`

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#655]
I really like this bar addition, can we just find an alternative to `NaN`?
<img width="1588" alt="Screenshot 2023-01-11 at 11 23 27" src="https://user-images.githubusercontent.com/32709181/211782323-3e24f419-edab-48e6-8fb4-d872f8407ee4.png">

_Originally posted by @rabah-khalek in https://github.com/Giskard-AI/giskard/issues/613#issuecomment-1378535910_

**Comment by Googleton** [comment]
Hey Rabah, do you have any specific scenario where this happens ? I can't find a reproductible case on my end

**Comment by rabah-khalek** [comment]
This is currently happening in the demo project of `German Credit Scoring`, in `models > Inspect > Inspect`. The inspection window I took screenshot of, disappears very quickly (so it's not crashing or anything) it's just that it's displaying a NaN.

**Comment by Googleton** [comment]
I understand where the issue happens in the UI, but for some reason on my end testing with every dataset I always get a number and no NaN 🤔

**Comment by rabah-khalek** [comment]
Then it's a byproduct of working from https://github.com/Giskard-AI/giskard/pull/618 (I'm not on `main`). Let's put a pin in it until we merge. Thanks!

**Comment by rabah-khalek** [comment]
closing as outdated
