### ISSUE TITLE
Feedback modal doesn't open for the second time after it's closed

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#675]
After the feedback modal is closed, the url isn't reset to `/feedbacks` and is still `/feedbacks/{id}`

**Comment by andreybavt** [comment]
@Googleton could you have a look at this small issue whenever you have time?

**Comment by Googleton** [comment]
Do you have more details for a reproduction? I can't get it to happen locally, I'm on main.

**Comment by kevinmessiaen** [comment]
Duplicate of #544

**Comment by andreybavt** [comment]
Good catch @kevinmessiaen, the first one was originally created 9 months ago 🙈
