### ISSUE TITLE
classification_label should support int value especialy for binary classification with 1 and 0

### ISSUE THREAD

**Issue by jmsquare** [Giskard-AI/giskard#684]
asked by Instant Gaming

**Comment by andreybavt** [comment]
TODO: to check what doesn't work

**Comment by rabah-khalek** [comment]
I recently used int `classification_label` in the sst2 notebook, and it did work. 
<img width="1111" alt="Screenshot 2023-02-07 at 10 14 44" src="https://user-images.githubusercontent.com/32709181/217202228-0039c635-277c-4cc7-a167-3f5979d0d75b.png">
in inspection:
<img width="1594" alt="Screenshot 2023-02-07 at 10 24 40" src="https://user-images.githubusercontent.com/32709181/217204514-1b268df7-0c33-4de9-a0f8-1727caf9a3f9.png">

Are we sure we noted correctly the issue they were having @jmsquare? 

this leads me to another question though, I don't think I understand this hint:
```py
    @staticmethod
    def _validate_label_with_target(classification_labels, target_values=None, target_name=None):
        if target_values is not None:
            if not is_string_dtype(target_values):
                print(
                    'Hint: "Your target variable values are numeric. '
                    "It is recommended to have Human readable string as your target values "
                    'to make results more understandable in Giskard."'
                )
```
Why do we give this hint @andreybavt? while we don't support this option `classification_label ={"No":0, "Yes":1}` in any case (to replace the int values with other string ones in the UI)
