### ISSUE TITLE
For binary classification, prediction_function should support an output of 1D array (and not necessarily 2D array)

### ISSUE THREAD

**Issue by jmsquare** [Giskard-AI/giskard#685]

**Comment by rabah-khalek** [comment]
This will become irrelevant in the new API as the user won't have to provide the predictions in a certain shape. Just the clf.

**Comment by andreybavt** [comment]
Some models could still return a 1D array, pytorch or custom models for example

**Comment by rabah-khalek** [comment]
you're right, you're right. Ok noted. Do we want a solution for this in 1.4.0?

**Comment by andreybavt** [comment]
nope

**Comment by rabah-khalek** [comment]
also in the case of binary classification, if the user give us 1D array, he has to tell us (or we need to tell him) to which classification_label it belongs. The benefit of 2D array is that it follows the same order as the classification_labels.
