### ISSUE TITLE
A prediction_function returning an int isn't validated and passes the upload

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#692]
A simple model like:
```
def model(df):
    return 5
```

passes the upload validation and causes inspector (both prediction and explanation) to break

**Comment by jmsquare** [comment]
For regression especially, we should not ask for numpy array as the output of model.
Same for binary classification.

**Comment by rabah-khalek** [comment]
Let us close this issue with the merge of https://github.com/Giskard-AI/giskard/pull/618 as it'll become irrelevant.

**Comment by andreybavt** [comment]
@rabah-khalek could you check that there's a unit test for it in the v2 branch?

**Comment by rabah-khalek** [comment]
Yes it's here: https://github.com/Giskard-AI/giskard/blob/9db3efc9918492c17333869b3dc6da852f0feb4a/python-client/tests/test_model_postprocess.py#L26
