### ISSUE TITLE
Test if the deamon connection ml worker is stable after 12 hours

### ISSUE THREAD

**Issue by jmsquare** [Giskard-AI/giskard#717]
- DigitRE has to re start ml worker every day
- Same for Intant gaming

**Comment by andreybavt** [comment]
I added a heartbeat for an ML Worker tcp connection to prevent it from being closed. On our dev instance there doesn't seem to be any issue (screenshot taken on 06/02 15:24):

![image](https://user-images.githubusercontent.com/7889985/216996542-f3ce4abe-9141-421b-a541-78ddfddfcece.png)
