### ISSUE TITLE
Create a demo instance of Giskard that is restarted every day

### ISSUE THREAD

**Issue by jmsquare** [Giskard-AI/giskard#729]
Problem: all our notebook examples are often executed using Colab. But there is no way to upload a model created in Colab in Giskard if Giskard is installed locally. For example, students do not often install Giskard in the Cloud and uses usually Colab. What could be a way for them to upload a model.

An easy way would be to have an open instance (demo.giskard.ai) that is accessible from Colab. This instance could be restarted and shut down every day.

**Comment by alexcombessie** [comment]
I would also advise we spend more time on the specification phase of this problem. Some questions:

- Are we sure that the solution of one server that is restarted everyday would fit the requirements? It means that people would lose their work.
- What is the maintenance cost associated with managing this open instance?
- Is this solution required if we offer a way to host on HF spaces?
