### ISSUE TITLE
[GSK-830] Business names

### ISSUE THREAD

**Issue by jmsquare** [Giskard-AI/giskard#833]
The user should :

* Add business names to the dataset columns (asked by Malakoff)
* Add business names to the categories of categorical columns (asked by Etam)

This can be an additional argument in the Dataset object where the user provides a list of mappings

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-830](https://linear.app/giskard/issue/GSK-830/business-names)</sub>

**Comment by jmsquare** [comment]
ok

**Comment by kevinmessiaen** [comment]
@jmsquare What do you think about a display in parenthesis for the business names in the UI:

![image.png](https://uploads.linear.app/5cb5c438-2552-41c0-89ac-b08d19e80d42/d9f297c5-b61f-46d8-b71c-6cfe4465fcbc/5080267d-a1cd-4295-87b3-d38728851eb7)

![image.png](https://uploads.linear.app/5cb5c438-2552-41c0-89ac-b08d19e80d42/f6fcae24-9fc1-4e12-8696-0d6f5714a607/60283304-3ab0-41a5-863d-df525c1a581a)

To provide in the API, we should simply have an optional dictionary I guess, something like this:

```
business_names = {
'Content': 'mail body'
}

category_business_names = {
  'days': {
    '1': 'Monday',
    ...
    '7': 'Sunday'
  }
}

Dataset(df, ...., business_names=business_names, category_business_names=category_business_names)
```

 

For editing in the UI I'm not sure where to put, maybe an edit in the `dataset`tab add a setting icon that open a modal to setup business names(⚙️):

![image.png](https://uploads.linear.app/5cb5c438-2552-41c0-89ac-b08d19e80d42/48b6db4e-b288-4898-8c95-4f778dc1b289/f68c57c7-bc8c-4723-9a5c-626423950ea1)

**Comment by andreybavt** [comment]
let's keep it for the last moment in case there's time. Test part is more important
