### ISSUE TITLE
[GSK-832] working on HuggingFace implementation

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#834]
A HuggingFace specific class for model-specific serialisation with the new upload API.

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-832](https://linear.app/giskard/issue/GSK-832/working-on-huggingface-implementation)</sub>

**Comment by andreybavt** [comment]
@jmsquare to contact altaroad and XHR for user tests

@andreybavt to start a user test document
