### ISSUE TITLE
[GSK-852] TensorFlow 2.11.0 not working on arm64

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#843]
Reported error by @Googleton :

```
Hash for tensorflow (2.11.0) from archive tensorflow-2.11.0-cp37-cp37m-macosx_10_14_x86_64.whl not found in known hashes (was: sha256:2c8bde1bbffc2475809d7624bfebf1aec33ca222b60897f65e45e10719450f8e)
```

To try:

* Setup arm instance on GCP
* try to install py env with tensorflow 2.9

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-852](https://linear.app/giskard/issue/GSK-852/tensorflow-2110-not-working-on-arm64)</sub>

**Comment by kevinmessiaen** [comment]
![image.png](https://uploads.linear.app/5cb5c438-2552-41c0-89ac-b08d19e80d42/88127b98-5fff-44bf-9cc1-3d563f1a3330/fb1522ee-7d3b-46a4-98a4-5111e01be166)

After setting tesorflow and tensorflow-text version to 2.9, I got the following error during the `gradle build` execution (python 3.7.16 arch x86_64 rosetta 2):

**Comment by rabah-khalek** [comment]
just for completeness: even though @kevinmessiaen's python is built on `x86_64`, his arch is `arm64`
