### ISSUE TITLE
[GSK-853] Incorrect test_disparate_impact error message

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#844]
python-client/giskard/ml_worker/testing/statistical_tests.py:198

The validation is done on target column value, but error message is about target column name

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-853](https://linear.app/giskard/issue/GSK-853/incorrect-test-disparate-impact-error-message)</sub>

**Comment by rabah-khalek** [comment]
fixed here: [https://github.com/Giskard-AI/giskard/pull/878](https://github.com/Giskard-AI/giskard/pull/878)
