### ISSUE TITLE
[GSK-856] Giskard gallery

### ISSUE THREAD

**Issue by jmsquare** [Giskard-AI/giskard#862]
The goal is to give a public access to [gallery.giskard.ai](http://gallery.giskard.ai).

In this environment, we should

* disable new artifact upload
* disable new filter creation/existing filter editing (because it’s arbitrary code)
* disable test creation/editing (because it’s arbitrary code)

The environment should contain german credit scoring, house pricing and twitter analysis data with feedback and a test suite

This demo environment will also be useful to document the tests

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-856](https://linear.app/giskard/issue/GSK-856/giskard-gallery)</sub>

**Comment by Inokinoki** [comment]
Replaced by GSK-1591
