### ISSUE TITLE
[GSK-859] Improve the `infer_column_types` in Dataset

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#866]
Today we implement a very minimal inference: [https://github.com/Giskard-AI/giskard/blob/8ea2077173bb739a6fa526e45fd1ec90ee0317ae/python-client/giskard/ml_worker/core/dataset.py#L60-L71](https://github.com/Giskard-AI/giskard/blob/8ea2077173bb739a6fa526e45fd1ec90ee0317ae/python-client/giskard/ml_worker/core/dataset.py#L60-L71)

We should do better. One way to do it, is implemented by DeepChecks: [https://github.com/deepchecks/deepchecks/blob/279ea72d8f5ff79e567cc6734a47b02311bbfb9d/deepchecks/utils/features.py#L348](https://github.com/deepchecks/deepchecks/blob/279ea72d8f5ff79e567cc6734a47b02311bbfb9d/deepchecks/utils/features.py#L348)

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-859](https://linear.app/giskard/issue/GSK-859/improve-the-infer-column-types-in-dataset)</sub>

**Comment by jmsquare** [comment]
@mattbit, is this solved. If yes can you put it as Done?

**Comment by mattbit** [comment]
Yep, it was handled by @rabah-khalek-khalek, it is done!
