### ISSUE TITLE
[GSK-874] Dataset related issues

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#870]
Couple of features that'll be nice to have:

* [ ] \~showing some dataset stats (like the number of entries, columns, etc.) on the frontend projects/datasets — @kevinmessiaen WDYT?\~
* [ ] \~showing the name of the dataset in the inspection window — @kevinmessiaen WDYT?\~
* [X] change infer_cat_column -> infer_column_types because we're also kind of guessing what is numeric and what is text, due to the "object" dtype. — solved in [https://github.com/Giskard-AI/giskard/commit/dce427bbe457ed3a42eb726878526d7c809bbc72](https://github.com/Giskard-AI/giskard/commit/dce427bbe457ed3a42eb726878526d7c809bbc72)
* [X] finding a final solution to the name of `feature_types` in Dataset (based on @mattbit's feedback) — solved in [https://github.com/Giskard-AI/giskard/pull/618/commits/b809e4ad7946dc137a505264f875e2189199987c](https://github.com/Giskard-AI/giskard/pull/618/commits/b809e4ad7946dc137a505264f875e2189199987c)
* [ ] Dataset inheriting from `pd.DataFrame`? (based on @mattbit's feedback) — @andreybavt WDYT?

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-874](https://linear.app/giskard/issue/GSK-874/dataset-related-issues)</sub>

**Comment by rabah-khalek** [comment]
we should also change infer_cat_column -> infer_column_types because we're also kind of guessing what is numeric and what is text, due to the "object" dtype.

**Comment by rabah-khalek** [comment]
last comment solved with [https://github.com/Giskard-AI/giskard/commit/dce427bbe457ed3a42eb726878526d7c809bbc72](https://github.com/Giskard-AI/giskard/commit/dce427bbe457ed3a42eb726878526d7c809bbc72)

**Comment by jmsquare** [comment]
To me this issue is not very urgent.

**Comment by andreybavt** [comment]
I also think that inheriting from pd.Dataframe may not be the best idea because it'll be more difficult to migrate other implementations like `arrow` (something HF did for their datasets).

**Comment by mattbit** [comment]
Same for me actually, by experience `pandas` objects are quite complex and it would be painful to maintain with inheritance.

**Comment by andreybavt** [comment]
anyway a rule of thumb is composition > inheritance, unless there are really good reasons for the opposite

**Comment by rabah-khalek** [comment]
Ok I will close this issue. I migrated the first two points to https://github.com/Giskard-AI/giskard/issues/910.
