### ISSUE TITLE
[GSK-880] Move docs to Sphinx

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#876]
<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-880](https://linear.app/giskard/issue/GSK-880/move-docs-to-sphinx)</sub>

**Comment by rabah-khalek** [comment]
After a discussion with @jmsquare , he pointed out that he's in favour of keeping GitBook for the guide documentation as it'll allow for non-tech people to also edit easily. I see his point, the only downsides to this I see are:

* homogeneity (the API reference will have a different stylings and format from the guide)
* referencing although manageable between gitbook's and sphinx's documentation, it'll be certainly more natural to have references and links within one framework.
