### ISSUE TITLE
[GSK-895] Caching preprocessed dataset in the UI

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#886]
for webedia for example, Preprocessing function takes a long time (10mins).

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-895](https://linear.app/giskard/issue/GSK-895/caching-preprocessed-dataset-in-the-ui)</sub>

**Comment by andreybavt** [comment]
WDYM "in UI"? Isn't it related to [https://github.com/Giskard-AI/giskard/pull/1002](https://github.com/Giskard-AI/giskard/pull/1002) ?

**Comment by rabah-khalek** [comment]
Yes, this is a duplicate of https://github.com/Giskard-AI/giskard/pull/1002
