### ISSUE TITLE
[GSK-898] Test output is not clear

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#888]
many test output keys (like unexpected_percent\_... ) is not clear.

We should also implement the `__repr__`  method to improve the visibility

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-898](https://linear.app/giskard/issue/GSK-898/test-output-is-not-clear)</sub>

**Comment by jmsquare** [comment]
The output of tests will change a lot once we introduce the debugging function.

**Comment by kevinmessiaen** [comment]
@jmsquare How do you think about some test result that can be displayed like that?

![image.png](https://uploads.linear.app/5cb5c438-2552-41c0-89ac-b08d19e80d42/510248a1-d125-4520-9419-ee56c5f11a11/c6ebe758-b2b6-44fb-9838-61c0f1c583df)

![image.png](https://uploads.linear.app/5cb5c438-2552-41c0-89ac-b08d19e80d42/f05ec591-9f7a-4a15-8674-e3fb193cce4f/24168fee-09cb-4578-95ab-dd6906f6168d)

**Comment by jmsquare** [comment]
That's nice! I don't think it's necessary to put all the path: giskard.ml_worker.testing.tests.performance… Maybe putting just test_f1 and the identifier of the tests (if there is any), it's ok!
