### ISSUE TITLE
[GSK-901] test related issues (Webedia)

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#891]
* User didn’t intuitively use test function object as a first argument of `add_test`, he wanted to call it directly
* it wasn’t clear that we have 2 modes of creating tests: function and class based

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-901](https://linear.app/giskard/issue/GSK-901/test-related-issues)</sub>

**Comment by andreybavt** [comment]
fixed by the new `GiskardTestMethod` implementation that allows to call `add_test(my_test(arg1=arg))` instead of `add_test(my_test, arg1=arg)`
