### ISSUE TITLE
[GSK-902] UI related issues

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#892]
* Giskard pull of the dev version does not work (tag api-v2) → wsl2? (should test on Windows)
* L’ui peut être intéressant pour le monitoring est voir l’ensemble des tests qui passent ou pas
* He wants to logs in the UI the execution of the suite in the notebook
* uploading a previously created license is not obvious at all atm (via “upload it”). Nicolas was tempted to create a new license.
* We should first upload without giving a project name

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-902](https://linear.app/giskard/issue/GSK-902/ui-related-issues)</sub>

**Comment by jmsquare** [comment]
Since all the points (except for the 4th ones) are not really relevant today. I mark this card as Done and create a new card on license
