### ISSUE TITLE
[GSK-920] Display some information about datasets (number of entries)

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#910]
* [ ] showing some dataset stats (like the number of entries, columns, etc.) on the frontend projects/datasets
* [ ] showing the name of the dataset in the inspection window

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-920](https://linear.app/giskard/issue/GSK-920/ui-small-improvements)</sub>

**Comment by shamim-io** [comment]
Hi @rabah-khalek I would like to work in this issue.

**Comment by Googleton** [comment]
Hey @shamim-io I've assigned the issue to you. Please open a PR when you've got some work to show, and don't hesitate to ask for help here or on our Discord !
