### ISSUE TITLE
[GSK-953] Where is giskard installation path on mac

### ISSUE THREAD

**Issue by Tonykaynoni** [Giskard-AI/giskard#922]
## Checklist

- [ ] I've searched the project's [`issues`](https://github.com/Giskard-AI/giskard/issues?q=is%3Aissue).

## ❓ Question

Where is giskard installation path on mac

<sub>[GSK-953](https://linear.app/giskard/issue/GSK-953/where-is-giskard-installation-path-on-mac)</sub>

**Comment by andreybavt** [comment]
Hi @Tonykaynoni ,

Giskard has 2 main components: server and ML Worker.

The server run in Docker, it creates 2 Docker volumes to store required data, to identify these volumes you may run a following command:
`docker volume ls | grep -E 'giskard|app-db-data'`


In case you start an ML Worker on your mac (by running `giskard worker start`) there will be a local directory created in `~/giskard-home` that will contain files related to the ML Worker operation
