### ISSUE TITLE
[GSK-955] doc related issues (Altaroad)

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#927]
* a clear link to Test Catalog from “Create custom test suite” is missing!
  * He does not find the test catalog link
  * He looks for documentation on Github README

deprecated or already done:

* It wasn’t clear to him that the feature_names should be the raw columns names and NOT the preprocessed names
* The section “Create custom test” in the doc is a bit misleading. We can remove “Custom”
* He finds that it is too oriented toward classificiation
* He has no clue about the test he wants to implement. Having clear tags about “regression” int the test catalog would have helped
* \~the difference between model and custom model is hard to get\~
* \~The word “Create” a model is not correct. I got confused because he already has a model created\~
* \~we should add a comment in the doc to avoid providing “classification_labels” if it’s a regression model\~
* putting `example` before `main parameters` in the doc made him completely missing the explanations (”j’ai du regarde ca”). He copy paste the example before reading the doc
  * Yet, examples are more important than the reference for him
    * if he doesn’t find an example snippet usually, he doesn’t even try it.
* Maybe we can remove feature_names from the code snippet? But we need to have a clear error message if we finally need that the user specify the feature_names
* for him, feature_names are the name of features used by the model, It not clear that feature_names is the parameter of the model

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-955](https://linear.app/giskard/issue/GSK-955/doc-related-issues-altaroad)</sub>

**Comment by alexcombessie** [comment]
@rabah-khalek-khalek can you update this with the latest changes?

**Comment by rabah-khalek** [comment]
Yep, this is part of my assigned issues, i tried first to prioritize the code based one. I'll work more on the doc tomorrow!
