### ISSUE TITLE
[GSK-981] Better output from the pydantic decorator validate_arguments

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#943]
* It’s not clear for that we expect a wrapped model `BaseModel` instead of a `clf`
  * The method `wrap_model` is confusing as it return a `BaseModel` , maybe a `WrappedModel` would be less confusing

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-981](https://linear.app/giskard/issue/GSK-981/better-output-from-the-pydantic-decorator-validate-arguments)</sub>

**Comment by jmsquare** [comment]
@rabah-khalek-khalek: is it solverd today? If yes, can you put the card as Done

**Comment by rabah-khalek** [comment]
Not done yet.

**Comment by rabah-khalek** [comment]
I didn't find the pydantic decorator to be super customizable, the other solution is to write our own decorator (which is tideous, a start is attempted here: [https://github.com/Giskard-AI/giskard/tree/task/pydantic_decorator](https://github.com/Giskard-AI/giskard/tree/task/pydantic_decorator) but not complete).

Maybe pydantic v2 would be already improved w.r.t the one we currently use ([https://docs.pydantic.dev/latest/blog/pydantic-v2/](https://docs.pydantic.dev/latest/blog/pydantic-v2/)).
