### ISSUE TITLE
[GSK-992] [GSK-991] Tests related issues (xhr)

### ISSUE THREAD

**Issue by rabah-khalek** [Giskard-AI/giskard#952]
* [X] the icon ❌ does not show in the IDE notebook
* [X] Results from f1 test does not seem meaningful, we should make some check about the data before running the tests. We should define an additional test outcome: `not applicable` or `error` or similar.
* [ ] \~He want to be able to pass a list of model to compare them\~
* [ ] \~he was not super sure about the moment the test is ran but guessed it right because he saw\~ `~.execute()~`
* [X] he passed a lambda to `slicing_function` and not a `SlicingFunction` object
  * [X] Maybe we can automatically wrap lambda into `SlicingFunction`
* [ ] \~he suggested to have (to give the idea that these are static):\~ For me it's too complicated

```
suite.add_data(wrapped_dataset, type='dataset', name="ref_dataset")
suite.add_param(name="old_model", type="model")
suite.add_preprocessing_hook(lambda...)
# and then:
suite.add_test(test_drif_psi(reference_dataset=suite.data["ref_dataset"])
#
```

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-992](https://linear.app/giskard/issue/GSK-992/[gsk-991]-tests-related-issues-xhr)</sub>

**Comment by jmsquare** [comment]
@kevinmessiaen: can you just make sure that the first point is working (the icon ❌ does not show in the IDE notebook) when we display the test result in the notebook? If yes you can put this card as "Done"
